# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.models.addresses_def import AddressesDef

class TestAddressesDef(unittest.TestCase):
    """AddressesDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressesDef:
        """Test AddressesDef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressesDef`
        """
        model = AddressesDef()
        if include_optional:
            return AddressesDef(
                addresses = [
                    royal-mail-address-codegen.models.address_summary_def.addressSummaryDef(
                        address_id = 'GB|RM|A|53946200', 
                        type = 'address', 
                        address_summary1 = 'addressLine3', 
                        address_summary2 = 'London', 
                        highlight = '0-2,6-4;0-3', )
                    ]
            )
        else:
            return AddressesDef(
        )
        """

    def testAddressesDef(self):
        """Test AddressesDef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
