# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.models.address_find_request_def import AddressFindRequestDef

class TestAddressFindRequestDef(unittest.TestCase):
    """AddressFindRequestDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressFindRequestDef:
        """Test AddressFindRequestDef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressFindRequestDef`
        """
        model = AddressFindRequestDef()
        if include_optional:
            return AddressFindRequestDef(
                address_text = '1 Elmgrove Rd, Weybridge KT13 8AA'
            )
        else:
            return AddressFindRequestDef(
                address_text = '1 Elmgrove Rd, Weybridge KT13 8AA',
        )
        """

    def testAddressFindRequestDef(self):
        """Test AddressFindRequestDef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
