# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.models.model404 import Model404

class TestModel404(unittest.TestCase):
    """Model404 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Model404:
        """Test Model404
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Model404`
        """
        model = Model404()
        if include_optional:
            return Model404(
                http_code = '400',
                http_message = 'Bad Request',
                more_information = '',
                errors = [
                    royal-mail-address-codegen.models.errors_def.errorsDef(
                        code = 'E1142', 
                        description = 'Barcode reference WL902730228GB is not recognised', 
                        cause = 'A mail item with that barcode cannot be located', 
                        resolution = 'Check barcode and resubmit', )
                    ]
            )
        else:
            return Model404(
                http_code = '400',
                http_message = 'Bad Request',
        )
        """

    def testModel404(self):
        """Test Model404"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
