# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_address_find(self) -> None:
        """Test case for address_find

        To find address summary with unique address id.
        """
        pass

    def test_address_retrieve(self) -> None:
        """Test case for address_retrieve

        To retrieve complete details for an address.
        """
        pass

    def test_address_verify(self) -> None:
        """Test case for address_verify

        To find matching addresses with DPS, AQI and AVC.
        """
        pass


if __name__ == '__main__':
    unittest.main()
