# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.models.address_record_def import AddressRecordDef

class TestAddressRecordDef(unittest.TestCase):
    """AddressRecordDef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressRecordDef:
        """Test AddressRecordDef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressRecordDef`
        """
        model = AddressRecordDef()
        if include_optional:
            return AddressRecordDef(
                address_id = 'GB|RM|A|53946128',
                domestic_id = '53946128',
                language = 'ENG',
                language_alternatives = 'ENG',
                department = 'Misc',
                company = 'Royal Mail',
                sub_building = 'Royal Mail',
                building_number = '5',
                building_name = 'Royal Mail',
                secondary_street = 'Abington street',
                street = 'Abington street',
                block = '10',
                neighbourhood = 'Royal Mail',
                district = 'Northamptonshire',
                city = 'London',
                line1 = 'Denmark Road',
                line2 = 'Abington avenue',
                line3 = 'GB|RM|A|53946128',
                line4 = 'GB|RM|A|53946128',
                line5 = 'GB|RM|A|53946128',
                admin_area_name = 'GB|RM|A|53946128',
                admin_area_code = 'GB|RM|A|53946128',
                province = 'GB|RM|A|53946128',
                province_name = 'GB|RM|A|53946128',
                province_code = 'GB|RM|A|53946128',
                postal_code = 'GB|RM|A|53946128',
                country_name = 'GB|RM|A|53946128',
                country_iso2 = 'GB|RM|A|53946128',
                country_iso3 = 'GB|RM|A|53946128',
                country_iso_number = 'GB|RM|A|53946128',
                sorting_number1 = 'GB|RM|A|53946128',
                sorting_number2 = 'GB|RM|A|53946128',
                barcode = 'GB|RM|A|53946128',
                po_box_number = 'GB|RM|A|53946128',
                label = 'GB|RM|A|53946128',
                type = 'GB|RM|A|53946128',
                data_level = 'GB|RM|A|53946128'
            )
        else:
            return AddressRecordDef(
        )
        """

    def testAddressRecordDef(self):
        """Test AddressRecordDef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
