# coding: utf-8

"""
    Royal Mail Address V1 (REST)

    Royal Mail API for Address matching. Eg. Finding addresses or retrieving address details.

    The version of the OpenAPI document: 1.0.9
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from royal_mail_address_codegen.models.address_verify_req_respdef import AddressVerifyReqRespdef

class TestAddressVerifyReqRespdef(unittest.TestCase):
    """AddressVerifyReqRespdef unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressVerifyReqRespdef:
        """Test AddressVerifyReqRespdef
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressVerifyReqRespdef`
        """
        model = AddressVerifyReqRespdef()
        if include_optional:
            return AddressVerifyReqRespdef(
                input = royal-mail-address-codegen.models.address_verifydef.addressVerifydef(
                    address_line1 = '1 Elmgrove Rd', 
                    address_line2 = 'Weybridge', 
                    address_line3 = 'string', 
                    post_town = 'Northamptonshire', 
                    county = 'Northamptonshire', 
                    postcode = 'NN15QS', ),
                dps = '1F'
            )
        else:
            return AddressVerifyReqRespdef(
        )
        """

    def testAddressVerifyReqRespdef(self):
        """Test AddressVerifyReqRespdef"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
